// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async bootstrapLoad() : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGet() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configSave(config: AppConfig) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_save", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingsUpdate(settings: Settings) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_update", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deviceDefaultsUpdate(settings: DeviceSettings) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("device_defaults_update", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appDiscoveryRefresh() : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_discovery_refresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appIconLoad(sourcePath: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_icon_load", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesCreate(profile: Profile) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_create", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesUpdate(profile: Profile) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_update", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesDelete(profileId: string) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_delete", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesList() : Promise<Result<DeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesAdd(modelKey: string) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_add", { modelKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesUpdateSettings(deviceKey: string, settings: DeviceSettings) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_update_settings", { deviceKey, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesUpdateProfile(deviceKey: string, profileId: string | null) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_update_profile", { deviceKey, profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesUpdateNickname(deviceKey: string, nickname: string | null) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_update_nickname", { deviceKey, nickname }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesResetToFactory(deviceKey: string) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_reset_to_factory", { deviceKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesRemove(deviceKey: string) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_remove", { deviceKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesSelect(deviceKey: string) : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_select", { deviceKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesSelectMock(deviceKey: string) : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_select_mock", { deviceKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyConfig(request: ImportLegacyConfigRequest) : Promise<Result<LegacyImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_config", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async debugClearLog() : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_clear_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appDiscoveryChangedEvent: AppDiscoveryChangedEvent,
debugEventEnvelope: DebugEventEnvelope,
deviceChangedEvent: DeviceChangedEvent,
engineStatusChangedEvent: EngineStatusChangedEvent,
profileChangedEvent: ProfileChangedEvent
}>({
appDiscoveryChangedEvent: "app-discovery-changed-event",
debugEventEnvelope: "debug-event-envelope",
deviceChangedEvent: "device-changed-event",
engineStatusChangedEvent: "engine-status-changed-event",
profileChangedEvent: "profile-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActionDefinition = { id: string; label: string; category: string; supported?: boolean }
export type AppConfig = { version: number; activeProfileId: string; profiles: Profile[]; managedDevices?: ManagedDevice[]; settings: Settings; deviceDefaults?: DeviceSettings }
export type AppDiscoveryChangedEvent = AppDiscoverySnapshot
export type AppDiscoverySnapshot = { suggestedApps: DiscoveredApp[]; browseApps: DiscoveredApp[]; lastScanAtMs: number | null; scanning: boolean }
export type AppDiscoverySource = "catalog" | "application_bundle" | "desktop_entry" | "start_menu_shortcut" | "registry" | "package" | "running_process"
export type AppMatcher = { kind: AppMatcherKind; value: string }
export type AppMatcherKind = "executable" | "executable_path" | "bundle_id" | "package_family_name"
export type AppearanceMode = "system" | "light" | "dark"
export type Binding = { control: LogicalControl; actionId: string }
export type BootstrapPayload = { config: AppConfig; availableActions: ActionDefinition[]; knownApps: KnownApp[]; appDiscovery: AppDiscoverySnapshot; supportedDevices: KnownDeviceSpec[]; layouts: DeviceLayout[]; engineSnapshot: EngineSnapshot; platformCapabilities: PlatformCapabilities; manualLayoutChoices: LayoutChoice[] }
export type DebugEvent = { kind: DebugEventKind; message: string; timestampMs: number }
export type DebugEventEnvelope = DebugEvent
export type DebugEventKind = "info" | "warning" | "gesture"
export type DeviceChangedEvent = DeviceInfo | null
export type DeviceControlCaptureKind = "os_button" | "os_hscroll" | "gesture" | "reprog_button"
export type DeviceControlDefaultSource = "explicit" | "recommendation"
export type DeviceControlSpec = { control: LogicalControl; label: string; captureKind: DeviceControlCaptureKind; defaultActionId: string; factoryDefaultActionId?: string | null; factoryDefaultLabel?: string | null; factoryDefaultSource?: DeviceControlDefaultSource | null; recommendedActionIds: string[]; sourceSlotIds: string[]; sourceSlotNames: string[]; reprogCids: number[] }
export type DeviceFingerprint = { identityKey: string | null; serialNumber: string | null; hidPath: string | null; interfaceNumber: number | null; usagePage: number | null; usage: number | null; locationId: number | null }
export type DeviceHotspot = { control: LogicalControl; label: string; summaryType: HotspotSummaryType; normX: number; normY: number; labelSide: LabelSide; labelOffX: number; labelOffY: number; isHscroll: boolean }
export type DeviceInfo = { key: string; modelKey: string; displayName: string; nickname: string | null; productId: number | null; productName: string | null; transport: string | null; source: string | null; uiLayout: string; imageAsset: string; supportedControls: LogicalControl[]; controls?: DeviceControlSpec[]; support: DeviceSupportMatrix; gestureCids: number[]; dpiMin: number; dpiMax: number; dpiInferred?: boolean; dpiSourceKind?: string | null; connected: boolean; batteryLevel: number | null; currentDpi: number; fingerprint?: DeviceFingerprint }
export type DeviceLayout = { key: string; label: string; imageAsset: string; imageWidth: number; imageHeight: number; interactive: boolean; manualSelectable: boolean; note: string; hotspots: DeviceHotspot[] }
export type DeviceSettings = { dpi: number; invertHorizontalScroll: boolean; invertVerticalScroll: boolean; macosThumbWheelSimulateTrackpad?: boolean; macosThumbWheelTrackpadHoldTimeoutMs?: number; gestureThreshold: number; gestureDeadzone: number; gestureTimeoutMs: number; gestureCooldownMs: number; manualLayoutOverride: string | null }
export type DeviceSupportLevel = "full" | "partial" | "experimental"
export type DeviceSupportMatrix = { level: DeviceSupportLevel; supportsBatteryStatus: boolean; supportsDpiConfiguration: boolean; hasInteractiveLayout: boolean; notes: string[] }
export type DiscoveredApp = { id: string; label: string; description: string | null; matchers: AppMatcher[]; iconAsset: string | null; sourceKinds: AppDiscoverySource[]; sourcePath: string | null; suggested: boolean }
export type EngineSnapshot = { devices: DeviceInfo[]; detectedDevices: DeviceInfo[]; activeDeviceKey: string | null; activeDevice: DeviceInfo | null; engineStatus: EngineStatus }
export type EngineStatus = { enabled: boolean; connected: boolean; activeProfileId: string; frontmostApp: string | null; selectedDeviceKey: string | null; debugMode: boolean; debugLog: DebugEvent[] }
export type EngineStatusChangedEvent = EngineStatus
export type HotspotSummaryType = "mapping" | "gesture" | "hscroll"
export type ImportLegacyConfigRequest = { sourcePath: string | null; rawJson: string | null }
export type KnownApp = { executable: string; label: string; iconAsset: string | null }
export type KnownDeviceSpec = { key: string; displayName: string; productIds: number[]; aliases: string[]; gestureCids: number[]; uiLayout: string; imageAsset: string; supportedControls: LogicalControl[]; controls?: DeviceControlSpec[]; support: DeviceSupportMatrix; dpiMin: number; dpiMax: number; dpiInferred?: boolean; dpiSourceKind?: string | null }
export type LabelSide = "left" | "right"
export type LayoutChoice = { key: string; label: string }
export type LegacyImportReport = { config: AppConfig; warnings: string[]; sourcePath: string | null; importedProfiles: number }
export type LogicalControl = "middle" | "gesture_press" | "gesture_left" | "gesture_right" | "gesture_up" | "gesture_down" | "back" | "forward" | "hscroll_left" | "hscroll_right" | "smartshift_toggle" | "mission_control_button" | "smart_zoom_button" | "precision_mode_button" | "dpi_button" | "emoji_button"
export type ManagedDevice = { id: string; modelKey: string; displayName: string; nickname: string | null; profileId?: string | null; identityKey?: string | null; settings?: DeviceSettings; createdAtMs: number; lastSeenAtMs: number | null; lastSeenTransport: string | null }
export type PlatformCapabilities = { platform: string; windowsSupported: boolean; macosSupported: boolean; liveHooksAvailable: boolean; liveHidAvailable: boolean; trayReady: boolean; mappingEngineReady: boolean; gestureDiversionAvailable: boolean; activeHidBackend: string; activeHookBackend: string; activeFocusBackend: string; hidapiAvailable: boolean; iokitAvailable: boolean }
export type Profile = { id: string; label: string; appMatchers: AppMatcher[]; bindings: Binding[] }
export type ProfileChangedEvent = { activeProfileId: string; frontmostApp: string | null }
export type Settings = { startMinimized: boolean; startAtLogin: boolean; appearanceMode: AppearanceMode; debugMode: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
