// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async bootstrapLoad() : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_load") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGet() : Promise<Result<AppConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configSave(config: AppConfig) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_save", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesCreate(profile: Profile) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_create", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesUpdate(profile: Profile) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_update", { profile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async profilesDelete(profileId: string) : Promise<Result<BootstrapPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("profiles_delete", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesList() : Promise<Result<DeviceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async devicesSelectMock(deviceKey: string) : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("devices_select_mock", { deviceKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importLegacyConfig(request: ImportLegacyConfigRequest) : Promise<Result<LegacyImportReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_legacy_config", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async debugClearLog() : Promise<Result<EngineSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("debug_clear_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
debugEventEnvelope: DebugEventEnvelope,
deviceChangedEvent: DeviceChangedEvent,
engineStatusChangedEvent: EngineStatusChangedEvent,
profileChangedEvent: ProfileChangedEvent
}>({
debugEventEnvelope: "debug-event-envelope",
deviceChangedEvent: "device-changed-event",
engineStatusChangedEvent: "engine-status-changed-event",
profileChangedEvent: "profile-changed-event"
})

/** user-defined constants **/



/** user-defined types **/

export type ActionDefinition = { id: string; label: string; category: string }
export type AppConfig = { version: number; activeProfileId: string; profiles: Profile[]; settings: Settings }
export type AppMatcher = { kind: AppMatcherKind; value: string }
export type AppMatcherKind = "executable"
export type AppearanceMode = "system" | "light" | "dark"
export type Binding = { control: LogicalControl; actionId: string }
export type BootstrapPayload = { config: AppConfig; availableActions: ActionDefinition[]; knownApps: KnownApp[]; layouts: DeviceLayout[]; engineSnapshot: EngineSnapshot; platformCapabilities: PlatformCapabilities; manualLayoutChoices: LayoutChoice[] }
export type DebugEvent = { kind: DebugEventKind; message: string; timestampMs: number }
export type DebugEventEnvelope = DebugEvent
export type DebugEventKind = "info" | "warning" | "gesture"
export type DeviceChangedEvent = DeviceInfo | null
export type DeviceHotspot = { control: LogicalControl; label: string; summaryType: HotspotSummaryType; normX: number; normY: number; labelSide: LabelSide; labelOffX: number; labelOffY: number; isHscroll: boolean }
export type DeviceInfo = { key: string; displayName: string; productId: number | null; productName: string | null; transport: string | null; source: string | null; uiLayout: string; imageAsset: string; supportedControls: LogicalControl[]; gestureCids: number[]; dpiMin: number; dpiMax: number; connected: boolean; batteryLevel: number | null; currentDpi: number }
export type DeviceLayout = { key: string; label: string; imageAsset: string; imageWidth: number; imageHeight: number; interactive: boolean; manualSelectable: boolean; note: string; hotspots: DeviceHotspot[] }
export type EngineSnapshot = { devices: DeviceInfo[]; activeDeviceKey: string | null; activeDevice: DeviceInfo | null; engineStatus: EngineStatus }
export type EngineStatus = { enabled: boolean; connected: boolean; activeProfileId: string; frontmostApp: string | null; selectedDeviceKey: string | null; debugMode: boolean; debugLog: DebugEvent[] }
export type EngineStatusChangedEvent = EngineStatus
export type HotspotSummaryType = "mapping" | "gesture" | "hscroll"
export type ImportLegacyConfigRequest = { sourcePath: string | null; rawJson: string | null }
export type KnownApp = { executable: string; label: string; iconAsset: string | null }
export type LabelSide = "left" | "right"
export type LayoutChoice = { key: string; label: string }
export type LegacyImportReport = { config: AppConfig; warnings: string[]; sourcePath: string | null; importedProfiles: number }
export type LogicalControl = "middle" | "gesture_press" | "gesture_left" | "gesture_right" | "gesture_up" | "gesture_down" | "back" | "forward" | "hscroll_left" | "hscroll_right"
export type PlatformCapabilities = { platform: string; windowsSupported: boolean; macosSupported: boolean; liveHooksAvailable: boolean; liveHidAvailable: boolean; trayReady: boolean; mappingEngineReady: boolean; gestureDiversionAvailable: boolean; activeHidBackend: string; activeHookBackend: string; activeFocusBackend: string; hidapiAvailable: boolean; iokitAvailable: boolean }
export type Profile = { id: string; label: string; appMatchers: AppMatcher[]; bindings: Binding[] }
export type ProfileChangedEvent = { activeProfileId: string; frontmostApp: string | null }
export type Settings = { startMinimized: boolean; startAtLogin: boolean; invertHorizontalScroll: boolean; invertVerticalScroll: boolean; dpi: number; gestureThreshold: number; gestureDeadzone: number; gestureTimeoutMs: number; gestureCooldownMs: number; appearanceMode: AppearanceMode; debugMode: boolean; deviceLayoutOverrides: Partial<{ [key in string]: string }> }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
